### ISSUE TITLE
MC Crashes

### ISSUE THREAD

**Issue by gcudupa01** [QPCrummer/Hopper-Speed-Simulator#10] opened 2024-08-05 06:58 UTC
Good morning,
I love your mod, however it's been crashing since updated to 1.21.  If I delete your mod and then open MC then it launches.
Please rectify if possible since there is no better mod than yours for increasing hopper speed as it is compatible with copper hopper mod also.
[launcher_log.txt](https://github.com/user-attachments/files/16491977/launcher_log.txt)

**Comment by QPCrummer** [comment] 2024-08-06 11:01
The issue is with my OmniHopper compatibility code not working in 1.21. Since my mod released before OmniHopper, I just reused my old code from 1.20.6. However it seems part of OmniHopper was rewritten, so I will have to update the compatibility

**Comment by QPCrummer** [comment] 2024-12-26 06:22
It appears as if OmniHopper isn't receiving updates anymore, so I am closing this issue

**Closed as completed by QPCrummer** 2024-12-26 06:22 UTC
